import { Tab, RecipeCategory, Settings, Recipe, DaySettings, RecipeTag } from './types';

export const TABS: Tab[] = [
  { id: 'planner', label: 'Planner' },
  { id: 'shopping', label: 'Shopping List' },
  { id: 'meals', label: 'Meals' },
  { id: 'log', label: 'Log' },
  { id: 'settings', label: 'Settings' },
];

export const DEFAULT_ALL_TAGS: Record<RecipeCategory, RecipeTag[]> = {
    [RecipeCategory.Breakfast]: ['high protein', 'easy to cook', 'on-the-go'],
    [RecipeCategory.Dinner]: ['affordable', 'high protein', 'easy to cook'],
    [RecipeCategory.Snack]: ['low cal', 'high protein', 'on-the-go'],
    [RecipeCategory.Drink]: ['low cal', 'easy to cook'],
};

export const INITIAL_RECIPES: Recipe[] = [
    {
        id: 'r_1',
        name: 'Lemon Herb Salad with Chickpeas and Chicken',
        description: 'A zesty, high-protein Mediterranean salad.',
        category: RecipeCategory.Dinner,
        tags: [],
        ingredients: '7 oz Chicken breast\n1/2 can Chickpeas\n2.5 cups Mixed greens\n1/4 Cucumber\n1/2 cup Cherry tomatoes\n1/8 Red onion\n1 tbsp Olive oil\n1/2 Lemon (juiced)\n1/2 tsp Dried oregano',
        instructions: '1. Grill and dice chicken.\n2. Whisk oil, lemon, and oregano.\n3. Toss all ingredients together.',
        macros: { calories: 450, protein: 42, carbs: 28, fat: 18 },
        healthScore: 9.5,
        scoreReasoning: 'Lean protein and high fiber.',
        usageIntensity: 'heavy',
        servings: 1
    },
    {
        id: 'r_2',
        name: 'Southwest Chicken Casserole',
        description: 'A comforting batch-cook favorite.',
        category: RecipeCategory.Dinner,
        tags: [],
        ingredients: '6 oz Chicken\n1/2 cup Black beans\n1/4 cup Corn\n1/4 cup Salsa\n1/4 cup Greek yogurt\n1/4 cup Cheddar\n2 Corn tortillas',
        instructions: '1. Mix all ingredients except tortillas.\n2. Layer tortillas and mixture in small dish.\n3. Bake at 375F for 20 mins.',
        macros: { calories: 420, protein: 48, carbs: 32, fat: 12 },
        healthScore: 8.5,
        scoreReasoning: 'Excellent fiber content.',
        usageIntensity: 'normal',
        servings: 1
    },
    {
        id: 'r_3',
        name: 'Mongolian Ground Beef Bowl',
        description: 'Sweet and savory lean beef over rice.',
        category: RecipeCategory.Dinner,
        tags: [],
        ingredients: '6 oz Lean ground beef\n1 cup Jasmine rice (cooked)\n1 tbsp Soy sauce\n1 tsp Brown sugar\n1/2 tsp Ginger\n1/2 tsp Garlic\n1 green onion\n1 cup Broccoli',
        instructions: '1. Brown beef.\n2. Add garlic/ginger.\n3. Stir in soy sauce and sugar.\n4. Serve over rice and steamed broccoli.',
        macros: { calories: 510, protein: 36, carbs: 54, fat: 16 },
        healthScore: 7.8,
        scoreReasoning: 'Balanced macros with fresh veg.',
        usageIntensity: 'light',
        servings: 1
    },
    {
        id: 'r_4',
        name: 'Greek Chicken Brown Rice Bowl',
        description: 'Mediterranean flavors with whole grain brown rice.',
        category: RecipeCategory.Dinner,
        tags: [],
        ingredients: '6 oz Chicken thighs\n3/4 cup Brown rice (cooked)\n1/4 Cucumber\n1/4 cup Cherry tomatoes\n5 Kalamata olives\n1 oz Feta\n1 tbsp Tzatziki',
        instructions: '1. Grill chicken.\n2. Cook rice.\n3. Assemble bowl with veg and feta.\n4. Top with chicken and tzatziki.',
        macros: { calories: 490, protein: 32, carbs: 40, fat: 22 },
        healthScore: 8.8,
        scoreReasoning: 'Good fats and slow carbs.',
        usageIntensity: 'heavy',
        servings: 1
    },
    {
        id: 'r_5',
        name: 'Salsa Chicken Burrito Bowl',
        description: 'Ultra-lean chicken slow-cooked in salsa.',
        category: RecipeCategory.Dinner,
        tags: [],
        ingredients: '6 oz Chicken breast\n1 tsp Taco seasoning\n1/4 cup Salsa\n3/4 cup Brown rice (cooked)\n1/2 cup Black beans\n1/4 cup Corn\n1 tbsp Greek yogurt\nCilantro',
        instructions: '1. Slow cook chicken with salsa.\n2. Shred chicken.\n3. Assemble with rice, beans and corn.',
        macros: { calories: 460, protein: 44, carbs: 58, fat: 6 },
        healthScore: 9.0,
        scoreReasoning: 'Very low fat, high volume.',
        usageIntensity: 'heavy',
        servings: 1
    },
    {
        id: 'r_6',
        name: 'Turkey & Sweet Potato Power Bowl',
        description: 'Complex carbs and lean protein.',
        category: RecipeCategory.Dinner,
        tags: [],
        ingredients: '6 oz Ground turkey\n1 Sweet potato\n1/4 cup Cottage cheese\n1 cup Spinach\n1/2 tsp Paprika',
        instructions: '1. Roast sweet potato cubes.\n2. Brown turkey.\n3. Wilt spinach.\n4. Top with cottage cheese.',
        macros: { calories: 410, protein: 38, carbs: 44, fat: 10 },
        healthScore: 9.2,
        scoreReasoning: 'High in Vitamin A and protein.',
        usageIntensity: 'normal',
        servings: 1
    },
    {
        id: 'r_7',
        name: 'High-Protein Chicken Fried Rice',
        description: 'A healthier take on the takeout classic.',
        category: RecipeCategory.Dinner,
        tags: [],
        ingredients: '5 oz Chicken\n1 Egg\n1 cup Rice (cooked)\n1/4 cup Peas & Carrots\n1 tbsp Soy sauce\n1/2 tsp Sesame oil',
        instructions: '1. Scramble egg.\n2. Cook chicken.\n3. Stir fry veg and rice.\n4. Combine all with soy sauce.',
        macros: { calories: 480, protein: 40, carbs: 52, fat: 12 },
        healthScore: 8.0,
        scoreReasoning: 'Protein boosted with extra egg.',
        usageIntensity: 'normal',
        servings: 1
    },
    {
        id: 'r_8',
        name: 'Chicken Teriyaki with Pineapple',
        description: 'Sweet pineapple and savory teriyaki glaze.',
        category: RecipeCategory.Dinner,
        tags: [],
        ingredients: '6 oz Chicken\n2 tbsp Teriyaki sauce\n1/4 cup Pineapple\n1 cup Broccoli\n1/2 cup White rice (cooked)',
        instructions: '1. Cook rice.\n2. Sauté chicken and broccoli.\n3. Add pineapple and sauce.\n4. Simmer until glazed.',
        macros: { calories: 530, protein: 34, carbs: 62, fat: 14 },
        healthScore: 7.5,
        scoreReasoning: 'Good micronutrients from fruit.',
        usageIntensity: 'light',
        servings: 1
    },
    {
        id: 'r_9',
        name: 'Baked Buffalo Chicken Strips',
        description: 'Spicy baked tenders with a buffalo kick.',
        category: RecipeCategory.Dinner,
        tags: [],
        ingredients: '6 oz Chicken tenderloins\n1/4 cup Panko\n2 tbsp Buffalo sauce\n1/2 Egg (for dredge)\n1 cup Brussels sprouts',
        instructions: '1. Coat chicken in panko.\n2. Bake chicken and sprouts at 400F.\n3. Toss chicken in buffalo sauce.',
        macros: { calories: 380, protein: 44, carbs: 24, fat: 12 },
        healthScore: 8.8,
        scoreReasoning: 'Lower calorie than fried.',
        usageIntensity: 'normal',
        servings: 1
    },
    {
        id: 'r_10',
        name: 'Protein Pasta with Turkey Meatballs',
        description: 'Lentil pasta and lean turkey meatballs.',
        category: RecipeCategory.Dinner,
        tags: [],
        ingredients: '5 oz Ground turkey\n2 oz Protein pasta (dry)\n1/2 cup Marinara\n1/2 cup Mushrooms\n1/2 tsp Italian seasoning',
        instructions: '1. Make meatballs.\n2. Cook pasta.\n3. Simmer meatballs in sauce.\n4. Toss with pasta.',
        macros: { calories: 540, protein: 46, carbs: 62, fat: 14 },
        healthScore: 8.2,
        scoreReasoning: 'High fiber from legume pasta.',
        usageIntensity: 'light',
        servings: 1
    },
    {
        id: 'r_11',
        name: 'Cottage Cheese Power Bowl',
        description: 'Quick protein-packed bowl with berries.',
        category: RecipeCategory.Breakfast,
        tags: [],
        ingredients: '1 cup Cottage cheese\n1/2 cup Berries\n1 tbsp Chia seeds',
        instructions: '1. Mix all in a bowl.',
        macros: { calories: 350, protein: 30, carbs: 25, fat: 12 },
        healthScore: 9.5,
        scoreReasoning: 'Perfect breakfast ratio.',
        usageIntensity: 'heavy',
        servings: 1,
        isAlsoSnack: true
    },
    {
        id: 'r_12',
        name: 'Greek Yogurt Power Bowl',
        description: 'High protein, probiotic, and fiber.',
        category: RecipeCategory.Breakfast,
        tags: ['high protein', 'easy to cook'],
        ingredients: '1 cup Greek yogurt\n1/2 cup Mixed berries\n1 tbsp Chia seeds',
        instructions: '1. Place yogurt in a bowl.\n2. Top with berries and chia seeds.',
        macros: { calories: 310, protein: 25, carbs: 32, fat: 9 },
        healthScore: 9.8,
        scoreReasoning: 'Excellent nutrient density.',
        usageIntensity: 'heavy',
        servings: 1,
        isAlsoSnack: true
    },
    {
        id: 'r_13',
        name: 'Greek Yogurt & Whey Bowl',
        description: 'Maximum protein with minimal effort.',
        category: RecipeCategory.Breakfast,
        tags: [],
        ingredients: '1 cup Greek yogurt\n1 scoop Whey protein\n1/2 cup Berries',
        instructions: '1. Stir whey into yogurt.\n2. Top with berries.',
        macros: { calories: 300, protein: 45, carbs: 20, fat: 2 },
        healthScore: 9.2,
        scoreReasoning: 'Very high protein density.',
        usageIntensity: 'heavy',
        servings: 1,
        isAlsoSnack: true
    },
    {
        id: 'r_14',
        name: 'Egg Whites & Sausage Bowl',
        description: 'Volume-heavy breakfast for fat loss.',
        category: RecipeCategory.Breakfast,
        tags: [],
        ingredients: '1 cup Egg whites\n2 Turkey sausages\n1/2 cup Veggies (peppers/onions)',
        instructions: '1. Scramble egg whites.\n2. Microwave sausage and veg.\n3. Mix together.',
        macros: { calories: 400, protein: 50, carbs: 15, fat: 15 },
        healthScore: 8.8,
        scoreReasoning: 'Highly satiating.',
        usageIntensity: 'normal',
        servings: 1
    },
    {
        id: 'r_15',
        name: 'Greek Yogurt Cup',
        description: 'Portable and simple individual snack.',
        category: RecipeCategory.Snack,
        tags: [],
        ingredients: '1 Individual Greek yogurt cup',
        instructions: '1. Eat cold.',
        macros: { calories: 100, protein: 15, carbs: 6, fat: 0 },
        healthScore: 9.0,
        scoreReasoning: 'Lean and efficient.',
        usageIntensity: 'heavy',
        servings: 1,
        isAlsoBreakfast: true
    },
    {
        id: 'r_16',
        name: 'Cottage Cheese Cup',
        description: 'Individual serve of protein-rich cottage cheese.',
        category: RecipeCategory.Snack,
        tags: [],
        ingredients: '1 Individual cottage cheese cup',
        instructions: '1. Eat cold.',
        macros: { calories: 100, protein: 14, carbs: 6, fat: 2 },
        healthScore: 9.0,
        scoreReasoning: 'Steady protein release.',
        usageIntensity: 'heavy',
        servings: 1,
        isAlsoBreakfast: true
    },
    {
        id: 'r_17',
        name: 'Beef Jerky',
        description: 'Savory dried beef snack high in protein.',
        category: RecipeCategory.Snack,
        tags: [],
        ingredients: '1 oz Beef jerky',
        instructions: '1. Eat as-is.',
        macros: { calories: 100, protein: 15, carbs: 2, fat: 2 },
        healthScore: 7.8,
        scoreReasoning: 'Watch sodium, but great protein.',
        usageIntensity: 'heavy',
        servings: 1
    },
    {
        id: 'r_18',
        name: 'Roasted Edamame',
        description: 'Crunchy plant-based protein with fiber.',
        category: RecipeCategory.Snack,
        tags: [],
        ingredients: '1/4 cup Roasted edamame',
        instructions: '1. Eat as-is.',
        macros: { calories: 130, protein: 12, carbs: 9, fat: 5 },
        healthScore: 9.4,
        scoreReasoning: 'Excellent plant nutrients.',
        usageIntensity: 'light',
        servings: 1
    },
    {
        id: 'r_19',
        name: 'Black Coffee with Almond Milk',
        description: 'Standard morning drink: 1 cup coffee with 1/2 cup unsweetened almond milk.',
        category: RecipeCategory.Drink,
        tags: ['low cal', 'easy to cook'],
        ingredients: '1 cup Brewed coffee\n1/2 cup Unsweetened almond milk',
        instructions: '1. Brew coffee.\n2. Stir in almond milk.',
        macros: { calories: 15, protein: 1, carbs: 1, fat: 1 },
        healthScore: 9.5,
        scoreReasoning: 'Low calorie, antioxidant rich.',
        usageIntensity: 'heavy',
        servings: 1,
        isDefaultDrink: true
    },
    {
        id: 'r_20',
        name: 'Turkey & Quest Chip Walking Taco',
        description: 'High-protein walking taco using protein chips.',
        category: RecipeCategory.Dinner,
        tags: ['high protein', 'easy to cook'],
        ingredients: '1 bag (1.1 oz) Quest Protein Chips (Taco flavor)\n4 oz Lean Ground Turkey (93% lean)\n1/4 cup Shredded Cheddar Cheese\n1/4 cup Shredded Lettuce\n1 tbsp Sour Cream\n2 tsp Low-sodium Taco Seasoning',
        instructions: '1. In a skillet over medium heat, cook the ground turkey until browned. Drain excess fat.\n2. Stir in the taco seasoning and water. Simmer for 2-3 minutes.\n3. Gently crush Quest chips inside the bag. Cut the top off.\n4. Spoon turkey into the bag.\n5. Top with cheese, lettuce, and sour cream. Eat with a fork.',
        macros: { calories: 460, protein: 49, carbs: 9, fat: 26 },
        healthScore: 7.5,
        scoreReasoning: 'High protein content.',
        usageIntensity: 'normal',
        servings: 1
    },
    {
        id: 'r_21',
        name: 'Loaded Quest Protein Nachos',
        description: 'Protein nachos using tortilla style protein chips.',
        category: RecipeCategory.Dinner,
        tags: [],
        ingredients: '1 bag Quest Tortilla Style Protein Chips (Taco or Chili Lime flavor)\n3 oz 93% lean ground turkey, cooked and seasoned\n1/2 cup fat-free refried beans\n1/4 cup shredded cheddar or Mexican blend cheese\n1 tbsp black olives, sliced\n2 tbsp diced tomatoes\n1/4 cup shredded lettuce\n1 tbsp sour cream',
        instructions: '1. Warm turkey and beans.\n2. Arrange chips on a plate.\n3. Layer beans and turkey over chips.\n4. Sprinkle cheese on top (microwave 15-20s if desired).\n5. Garnish with lettuce, tomatoes, olives, and sour cream.\n6. Serve immediately.',
        macros: { calories: 480, protein: 45, carbs: 15, fat: 28 },
        healthScore: 8.0,
        scoreReasoning: 'High protein with controlled fats.',
        usageIntensity: 'normal',
        servings: 1
    },
    {
        id: 'r_22',
        name: 'Zesty Salmon & Brown Rice Bowl',
        description: 'Salmon paired with creamy avocado and fresh spinach.',
        category: RecipeCategory.Dinner,
        tags: [],
        ingredients: '6 oz Salmon\n2 cups Spinach\n1/2 Avocado\n1/4 cup Brown Rice (dry)\n1/4 Cucumber\n1 tsp Olive oil\n1/4 Lemon (juiced)',
        instructions: '1. Bake salmon at 400F for 12 mins.\n2. Cook brown rice.\n3. Assemble bowl with spinach base.\n4. Top with salmon, rice, cucumber, and avocado.\n5. Drizzle with olive oil and lemon juice.',
        macros: { calories: 580, protein: 38, carbs: 32, fat: 34 },
        healthScore: 9.0,
        scoreReasoning: 'Rich in Omega-3s and healthy fats.',
        usageIntensity: 'normal',
        servings: 1
    },
    {
        id: 'r_23',
        name: 'Italian Prosciutto "Sushi" Rolls',
        description: 'Savory rolls with prosciutto, pesto, and arugula.',
        category: RecipeCategory.Snack,
        tags: [],
        ingredients: '4-5 slices Prosciutto (approx. 3 oz)\n1.5 tbsp Basil Pesto (ensure gluten-free)\n1 handful Fresh Arugula\n1.5 oz Fresh Mozzarella (sliced thin)\n2 tbsp Sun-dried Tomatoes (chopped)\nPinch of Sea Salt\n1 tbsp Balsamic Glaze',
        instructions: '1. Lay plastic wrap. Arrange prosciutto slices overlapping. 2. Spread pesto gently. 3. Top with arugula, mozzarella, and tomatoes. 4. Tightly roll up. 5. Refrigerate 10 mins. 6. Slice into bite-sized rounds. Garnish with sea salt and balsamic.',
        macros: { calories: 280, protein: 18, carbs: 6, fat: 22 },
        healthScore: 6.2,
        scoreReasoning: 'High sodium from cured meat, but good protein.',
        usageIntensity: 'light',
        servings: 1
    },
    {
        id: 'r_24',
        name: 'Chocolate Protein Oat Scramble & Yogurt Bowl',
        description: 'A unique high-protein oat bowl with scrambled oats.',
        category: RecipeCategory.Breakfast,
        tags: ['high protein'],
        ingredients: '1 medium banana (divided use)\n1/2 cup gluten-free rolled oats\n2 large eggs\n1/2 scoop (approx 15g) protein powder\n1 tsp cocoa powder\n1/4 tsp cinnamon\n3/4 cup plain non-fat Greek yogurt\n1 tsp honey\n3 strawberries (sliced)\n1 tbsp unsweetened coconut flakes',
        instructions: '1. Mash half the banana. Mix with oats, eggs, protein powder, cocoa, and cinnamon. 2. Heat non-stick skillet. Pour mixture and scramble for 4-5 mins. 3. Add yogurt to a bowl. Top with oat scramble, banana slices, strawberries, and coconut.',
        macros: { calories: 420, protein: 38, carbs: 48, fat: 12 },
        healthScore: 9.2,
        scoreReasoning: 'Excellent fiber and protein balance.',
        usageIntensity: 'light',
        servings: 1
    },
    {
        id: 'r_25',
        name: 'Copycat Kirkland Bacon & Gouda Egg Bites',
        description: 'Smoky, cheesy sous-vide style egg bites.',
        category: RecipeCategory.Breakfast,
        tags: ['high protein'],
        ingredients: '2 large eggs\n2 tbsp cottage cheese (4% fat)\n2 tbsp shredded Gouda cheese\n1 slice bacon (cooked and crumbled)\npinch of sea salt and black pepper',
        instructions: '1. Blend eggs, cottage cheese, salt, pepper until smooth. 2. Spray silicone mold. Divide bacon and Gouda into 2 cups. 3. Pour egg mixture over. 4. Bake at 300F with water tray for 20-25 mins. 5. Cool before popping out.',
        macros: { calories: 310, protein: 22, carbs: 4, fat: 24 },
        healthScore: 7.2,
        scoreReasoning: 'Good protein, moderate fat from cheese/bacon.',
        usageIntensity: 'normal',
        servings: 1
    },
    {
        id: 'r_26',
        name: 'Gluten-Free Kodiak Protein Pancakes with Creamy Topping',
        description: 'Quick protein-packed pancakes with a yogurt-cheese whip.',
        category: RecipeCategory.Breakfast,
        tags: ['high protein', 'easy to cook'],
        ingredients: '1/2 cup Kodiak Cakes Gluten-Free Mix\n1/2 cup water (or almond milk)\n1/4 cup non-fat plain Greek yogurt\n1/4 cup low-fat cottage cheese\nCooking spray',
        instructions: '1. Mix Kodiak and water. 2. Cook on greased skillet until bubbles pop, then flip. 3. Whip yogurt and cottage cheese together. 4. Stack pancakes and top with the creamy mixture.',
        macros: { calories: 350, protein: 28, carbs: 32, fat: 6 },
        healthScore: 9.0,
        scoreReasoning: 'High protein and complex carbs.',
        usageIntensity: 'light',
        servings: 1
    },
    {
        id: 'r_27',
        name: 'Store-Bought David Bar Cookie Dough (Gluten-Free)',
        description: 'A quick, portable protein snack.',
        category: RecipeCategory.Snack,
        tags: ['on-the-go'],
        ingredients: '1 package Pre-made David Bar (Cookie Dough flavor)',
        instructions: '1. Remove from packaging. 2. Enjoy as a snack or pre-workout. 3. Optional: Microwave 10s for warm texture.',
        macros: { calories: 210, protein: 20, carbs: 24, fat: 8 },
        healthScore: 7.0,
        scoreReasoning: 'Convenient processed snack with good macros.',
        usageIntensity: 'normal',
        servings: 1
    }
];

const DEFAULT_DAY_SETTINGS: DaySettings = {
    breakfast: true,
    lunch: true,
    dinner: true,
    snack: true
};

export const DEFAULT_SETTINGS: Settings = {
    planDurationWeeks: 1,
    numberOfPeople: 2,
    useLeftoverForLunch: true,
    autoAdjustPortions: true,
    fudgeRoom: 250,
    minMealGapDays: 2,
    dinnersPerWeek: 4,
    breakfastsPerWeek: 3,
    snacksPerWeek: 3,
    lunchesPerWeek: 0,
    defaultDrinksPerPersonPerDay: 2,
    maxUsesPerRecipePerPlan: 4,
    leftoverStrategy: 'random',
    dailyMeals: {
        Monday: { ...DEFAULT_DAY_SETTINGS },
        Tuesday: { ...DEFAULT_DAY_SETTINGS },
        Wednesday: { ...DEFAULT_DAY_SETTINGS },
        Thursday: { ...DEFAULT_DAY_SETTINGS },
        Friday: { ...DEFAULT_DAY_SETTINGS },
        Saturday: { ...DEFAULT_DAY_SETTINGS },
        Sunday: { ...DEFAULT_DAY_SETTINGS }
    },
    people: [
        { name: 'Benjamin', goals: { calories: 2000, protein: 30, carbs: 40, fat: 30 } },
        { name: 'Kathleen', goals: { calories: 1750, protein: 30, carbs: 40, fat: 30 } },
    ],
    blacklistedIngredients: ['quinoa'],
    minimalIngredients: ['gluten'],
};